// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"bitmagnet-io/bitmagnet/internal/bloom"
	"time"
)

const TableNameBloomFilter = "bloom_filters"

// BloomFilter mapped from table <bloom_filters>
type BloomFilter struct {
	Key       string                  `gorm:"column:key;primaryKey" json:"key"`
	Filter    bloom.StableBloomFilter `gorm:"column:bytes;not null" json:"bytes"`
	CreatedAt time.Time               `gorm:"column:created_at;not null;<-:create" json:"createdAt"`
	UpdatedAt time.Time               `gorm:"column:updated_at;not null" json:"updatedAt"`
}

// TableName BloomFilter's table name
func (*BloomFilter) TableName() string {
	return TableNameBloomFilter
}
